version: '2'
services:
  locacaoimoveis-app:
    image: locacaoimoveis
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://locacaoimoveis-postgresql:5432/locacaoImoveis
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://locacaoimoveis-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://locacaoimoveis-elasticsearch:9200
    ports:
      - 8080:8080
  locacaoimoveis-postgresql:
    extends:
      file: postgresql.yml
      service: locacaoimoveis-postgresql
  locacaoimoveis-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: locacaoimoveis-elasticsearch
